### PR TITLE
Feature/add update ubuntu containers again

### PR DESCRIPTION
**Pull request by ewhelan**
Done correctly this time (I hope) ...

Add Ubuntu (22.04 --> 24.10) containers that will compile Harmonie 46h1 and 49T2h code and run Testbed.

### CODE REVIEW

**Comment by ovignes** [comment]
My previous comment was actually about using git@github.com:ewhelan/HarmonieCSC.git in the instructions
instead of git@github.com:Hirlam/HarmonieCSC.git
But since those are only comments I guess it is fine.
I might be able to test on ubuntu 22.04, but that won't happen today.

**Comment by ewhelan** [comment]
> My previous comment was actually about using [git@github.com](mailto:git@github.com):ewhelan/HarmonieCSC.git in the instructions instead of [git@github.com](mailto:git@github.com):Hirlam/HarmonieCSC.git But since those are only comments I guess it is fine. I might be able to test on ubuntu 22.04, but that won't happen today.

Thanks @ovignes. Hopefully latest commit addresses this.

**Review by ovignes — APPROVED** [review]
Approved (without testing, don't wait for that). I'm sure you have tested yourself.

**Comment by ewhelan** [comment]
Thanks @ovignes. Well tested for pending CY46h1 and CY49T2h PRs. Will merge now.

**Pull request merged**
